import type { Locale } from "@/lib/i18n/messages";

export type LegalSection = {
  title: string;
  paragraphs: string[];
};

export type LegalDocument = {
  title: string;
  lastUpdated: string;
  sections: LegalSection[];
};

const termsZh: LegalDocument = {
  title: "服務條款",
  lastUpdated: "最後更新：2026 年 3 月 26 日",
  sections: [
    {
      title: "1. 營運者與聯絡方式",
      paragraphs: [
        "本服務（包括 https://hkbookkeep.harbix.app、https://sgbookkeep.harbix.app 及 https://twbookkeep.harbix.app，以下統稱「本服務」）由 Harbix 營運。聯絡方式：電郵 bookkeep@harbix.app。",
      ],
    },
    {
      title: "2. 服務內容",
      paragraphs: [
        "本服務為網上工具，協助使用者記錄收支、分類及匯出報表。本服務並非會計、稅務或法律專業服務。本服務所產生之任何報表、稅務計算或分析僅供參考，不構成稅務或法律意見。特別針對新加坡用戶：本服務僅為自助式記帳工具，並不提供任何由新加坡內陸稅務局（IRAS）定義之專業稅務代理服務。",
      ],
    },
    {
      title: "3. 帳戶與登入",
      paragraphs: [
        "你須提供準確資料並妥善保管帳戶。你可使用我哋支援嘅登入方式（例如 Google、電郵及密碼）。若發現未經授權使用，請立即聯絡我哋。",
      ],
    },
    {
      title: "4. 訂閱、試用、定價與付款（Stripe）",
      paragraphs: [
        "本服務收費以網站結帳頁面顯示為準。例如：香港地區：港幣 38 元／月 或 港幣 380 元／年；新加坡地區：新幣 6.5 元／月 或 新幣 65 元／年；台灣地區：台幣 150 元／月 或 台幣 1500 元／年。新帳戶享 14 日免費試用。試用結束後若選擇訂閱，須經 Stripe 完成付款。所有付款由第三方 Stripe 處理，你同意受 Stripe 條款約束。",
        "你可透過我哋提供嘅連結進入 Stripe Customer Portal，以更新付款方式、查閱帳單及取消訂閱。取消之生效日及計費週期以 Stripe 及你帳戶狀態為準。",
      ],
    },
    {
      title: "5. 試用結束、訂閱中斷與「只讀」",
      paragraphs: [
        "試用期結束時，若你未成功完成付費訂閱，你嘅帳戶可進入「只讀」：你可瀏覽現有資料及匯出 CSV／PDF，但不可新增、修改或刪除資料，直至付費成功為止。",
        "付費訂閱因任何原因中斷或屆滿未續（包括你喺 Portal 取消或付款失敗），帳戶亦可進入「只讀」（可瀏覽及匯出 CSV／PDF），直至重新訂閱成功為止。",
        "實際狀態以系統顯示及 Stripe 同步為準。",
      ],
    },
    {
      title: "6. 取消訂閱與退款",
      paragraphs: [
        "取消訂閱：請使用 Stripe Customer Portal 操作。一般情況下，已開始之計費週期不會因中途取消而按比例退款；你可在該週期內按條款繼續使用服務直至該週期結束（實際以 Stripe 設定及帳戶狀態為準）。",
        "退款：除適用法例另有強制規定外，已收取之訂閱費用一般不設中期退款。如你懷疑重複扣款、錯誤扣款或未授權交易，請先透過 Customer Portal 查閱紀錄，或聯絡 bookkeep@harbix.app，我哋會協助與 Stripe 紀錄核對。",
      ],
    },
    {
      title: "7. 資料與刪除",
      paragraphs: [
        "個人資料之收集、使用、保留及刪除，請參閱下方《私隱政策》（包括試用結束後 T+30／T+60／T+90 之處理）。",
        "你可於登入後使用「帳號」頁面刪除帳戶及相關資料，詳情以《私隱政策》為準。",
      ],
    },
    {
      title: "8. 可接受使用",
      paragraphs: [
        "你唔可利用本服務從事違法、侵害他人權利、或干擾系統安全之行為。我哋有權喺合理情況下暫停或終止帳戶。",
      ],
    },
    {
      title: "9. 免責與責任限制",
      paragraphs: [
        "在法律允許嘅最大範圍內，本服務按「現狀」提供。Harbix 嘅責任上限為你在索賠發生前 12 個月內實際支付之費用總額。若你所在地之法例（如台灣消費者保護法或新加坡相關法令）不允許排除特定責任，則該等免責條款在法例禁止範圍內不予適用。",
      ],
    },
    {
      title: "10. 條款變更",
      paragraphs: [
        "我哋可更新本條款並於網站刊登。你繼續使用即表示接受修訂（重大變更建議另發電郵通知）。",
      ],
    },
    {
      title: "11. 準據語言",
      paragraphs: [
        "本條款以繁體中文書寫；如有翻譯版本，以中文版本優先解釋（除非法例另有規定）。",
      ],
    },
    {
      title: "12. 準據法與管轄權",
      paragraphs: [
        "本條款受香港特別行政區法律管轄並按其解釋。凡因本服務引起之任何爭議，均受香港法院之專屬管轄權管轄。",
      ],
    },
  ],
};

const termsEn: LegalDocument = {
  title: "Terms of Service",
  lastUpdated: "Last updated: 26 March 2026",
  sections: [
    {
      title: "1. Operator and contact",
      paragraphs: [
        "This service (including https://hkbookkeep.harbix.app, https://sgbookkeep.harbix.app and https://twbookkeep.harbix.app, collectively the “Service”) is operated by Harbix. Contact: bookkeep@harbix.app.",
      ],
    },
    {
      title: "2. The service",
      paragraphs: [
        "The Service is an online tool to help users record income and expenses, categorise transactions, and export reports. It is not accounting, tax, or legal professional service. Any report, tax calculation, or analysis generated by the Service is for reference only and does not constitute tax or legal advice. For Singapore users specifically: the Service is a self-service bookkeeping tool only and does not provide any professional tax agent service as defined by IRAS.",
      ],
    },
    {
      title: "3. Accounts and sign-in",
      paragraphs: [
        "You must provide accurate information and keep your account secure. You may sign in using supported methods (e.g. Google, email and password). If you notice unauthorised use, contact us immediately.",
      ],
    },
    {
      title: "4. Subscription, trial, pricing, and payments (Stripe)",
      paragraphs: [
        "Fees follow the website checkout page. For example: Hong Kong: HK$38/month or HK$380/year; Singapore: S$6.5/month or S$65/year; Taiwan: NT$150/month or NT$1500/year. New accounts receive a 14-day free trial. If you subscribe after trial, payment is completed through Stripe. All payments are handled by third-party Stripe, and you agree to Stripe terms.",
        "You may use our links to open the Stripe Customer Portal to update payment methods, view invoices, and cancel subscriptions. Effective cancellation dates and billing cycles follow Stripe and your account status.",
      ],
    },
    {
      title: "5. After trial, subscription lapse, and read-only",
      paragraphs: [
        "If you do not complete a paid subscription when the trial ends, your account may become read-only: you can view existing data and export CSV/PDF, but cannot add, edit, or delete data until payment succeeds.",
        "If a paid subscription ends or lapses without renewal (including cancellation in the Portal or payment failure), the account may also become read-only (view and export CSV/PDF) until you resubscribe successfully.",
        "Actual status follows the product UI and Stripe sync.",
      ],
    },
    {
      title: "6. Cancellation and refunds",
      paragraphs: [
        "To cancel, use the Stripe Customer Portal. Generally, a billing period that has already started is not refunded pro rata if you cancel mid-cycle; you may continue using the service for that period as applicable (subject to Stripe settings and your account).",
        "Except where mandatory law requires otherwise, subscription fees already paid are generally not refunded mid-term. If you suspect duplicate charges, errors, or unauthorised transactions, check the Portal first or email bookkeep@harbix.app and we will help reconcile with Stripe records.",
      ],
    },
    {
      title: "7. Data and deletion",
      paragraphs: [
        "For collection, use, retention, and deletion of personal data, see the Privacy Policy below (including T+30 / T+60 / T+90 after trial end).",
        "After sign-in you may delete your account and related data from the Account page, as described in the Privacy Policy.",
      ],
    },
    {
      title: "8. Acceptable use",
      paragraphs: [
        "You must not use the service unlawfully, infringe others’ rights, or harm system security. We may suspend or terminate accounts where reasonable.",
      ],
    },
    {
      title: "9. Disclaimer and liability cap",
      paragraphs: [
        "To the fullest extent permitted by law, the Service is provided “as is”. Harbix’s liability cap is the total fees you actually paid in the 12 months before the claim. If laws in your jurisdiction (such as Taiwan consumer protection rules or relevant Singapore laws) do not allow exclusion of certain liabilities, those exclusions do not apply where prohibited.",
      ],
    },
    {
      title: "10. Changes",
      paragraphs: [
        "We may update these terms on the website. Continued use means acceptance (material changes should ideally be emailed separately).",
      ],
    },
    {
      title: "11. Language",
      paragraphs: [
        "These terms are written in Traditional Chinese; if there is a translation, the Chinese version prevails except where law says otherwise.",
      ],
    },
    {
      title: "12. Governing law and jurisdiction",
      paragraphs: [
        "These Terms are governed by and construed in accordance with the laws of the Hong Kong Special Administrative Region. Any dispute arising from the Service is subject to the exclusive jurisdiction of the courts of Hong Kong.",
      ],
    },
  ],
};

const privacyZh: LegalDocument = {
  title: "私隱政策",
  lastUpdated: "最後更新：2026 年 3 月 26 日",
  sections: [
    {
      title: "1. 資料控制者",
      paragraphs: [
        "負責處理你個人資料嘅一方為 Harbix。聯絡：bookkeep@harbix.app。",
      ],
    },
    {
      title: "2. 我哋收集咩資料",
      paragraphs: [
        "帳戶資料：例如電郵地址、登入識別（透過 Supabase Auth 等）。",
        "你主動輸入嘅業務資料：例如生意簿名稱、交易紀錄、分類、金額、幣種、備註。",
        "你上載嘅檔案：例如收據影像（儲於 Supabase Storage）。",
        "技術資料：例如 IP、裝置類型、瀏覽記錄（視乎託管商／分析設定；MVP 宜最小化）。",
        "付款資料：信用卡等付款資料由 Stripe 直接處理，我哋不會喺自己伺服器儲存你完整卡號；我哋可能透過 Stripe 收到訂閱狀態、客戶識別碼等。",
      ],
    },
    {
      title: "3. 點解要收集（用途）",
      paragraphs: [
        "提供、維持及改善記帳功能；處理訂閱及試用；發送服務相關電郵（例如電郵驗證／重設密碼、試用／訂閱提醒、試用結束後第 30 日之資料提醒）；防欺詐、保安及法例要求；回覆你透過表單提出嘅查詢（經第三方電郵服務以 bookkeep@harbix.app 發送或接收相關通知）。",
      ],
    },
    {
      title: "4. 法律基礎與地區適用",
      paragraphs: [
        "我哋根據適用之個人資料保護法例（包括但不限於香港 PDPO、新加坡 PDPA 及台灣《個人資料保護法》）處理資料。資料係為履行服務合約、徵得你同意、或為合法權益（如系統安全）而處理。",
      ],
    },
    {
      title: "5. 第三方服務提供者（副處理者）",
      paragraphs: [
        "我哋使用（或可能使用）以下類別服務，佢哋或會喺境外處理資料：Stripe（付款）、Supabase（資料庫、認證、檔案儲存）、第三方收發電郵（例如 Resend）、Vercel（網站託管）等。佢哋有其獨立私隱政策。",
      ],
    },
    {
      title: "6. 資料保留（包括試用結束後）",
      paragraphs: [
        "試用結束（T+30）：發出電郵提醒。",
        "試用結束（T+60）：若未訂閱，我哋可刪除帳戶及相關業務資料。",
        "試用結束（T+90）：徹底清除剩餘備份或收據影像檔案（Supabase Storage）。",
        "手動刪除：透過「帳號」頁面刪除，系統將即時啟動清除程序。",
      ],
    },
    {
      title: "7. 保安",
      paragraphs: [
        "我哋採取合理技術及組織措施（例如 HTTPS、存取控制、供應商之安全功能）。互聯網傳輸並非百分之百安全。",
      ],
    },
    {
      title: "8. 你的權利",
      paragraphs: [
        "你可聯絡 bookkeep@harbix.app 要求查閱、更正、或（在法例允許下）刪除個人資料。",
        "登入後前往「帳號」頁面可刪除帳戶：系統會刪除你嘅登入帳戶、業務資料（生意簿／交易／分類）、以及已上載收據檔案，並會盡力取消 Stripe 訂閱及刪除本應用程式所關聯之 Stripe 客戶資料；付款機構可能按其政策保留部份帳務紀錄。",
      ],
    },
    {
      title: "9. Cookie",
      paragraphs: [
        "我哋使用必要 Cookie 以維持登入及安全；若日後加入分析／營銷類 Cookie，將更新本政策並在需要時徵求同意。",
      ],
    },
    {
      title: "10. 兒童",
      paragraphs: [
        "本服務唔擬向 18 歲以下人士提供；如發現誤收集，請聯絡我哋刪除。",
      ],
    },
    {
      title: "11. 政策修訂",
      paragraphs: [
        "我哋可更新本政策；重大變更將透過網站或電郵通知。",
      ],
    },
  ],
};

const privacyEn: LegalDocument = {
  title: "Privacy Policy",
  lastUpdated: "Last updated: 26 March 2026",
  sections: [
    {
      title: "1. Data controller",
      paragraphs: [
        "The data controller is Harbix. Contact: bookkeep@harbix.app.",
      ],
    },
    {
      title: "2. What we collect",
      paragraphs: [
        "Account data: e.g. email address and login identifiers (via Supabase Auth, etc.).",
        "Business data you enter: e.g. ledger names, transactions, categories, amounts, currencies, notes.",
        "Files you upload: e.g. receipt images (stored in Supabase Storage).",
        "Technical data: e.g. IP, device type, browsing logs (depends on hosting/analytics setup; keep MVP minimal).",
        "Payment data: card details are handled directly by Stripe; we do not store full card numbers on our servers; we may receive subscription status and customer IDs from Stripe.",
      ],
    },
    {
      title: "3. Why we collect it",
      paragraphs: [
        "To provide, maintain, and improve bookkeeping features; to handle subscriptions and trials; to send service emails (e.g. email verification / password reset, trial/subscription reminders, day-30 reminder after trial end); for fraud prevention, security, and legal compliance; to respond to enquiries from forms (via a transactional email provider, using bookkeep@harbix.app for related notifications).",
      ],
    },
    {
      title: "4. Legal basis and regional applicability",
      paragraphs: [
        "We process data under applicable personal data protection laws, including but not limited to Hong Kong PDPO, Singapore PDPA, and Taiwan’s Personal Data Protection Act. Processing is based on performance of our service contract, your consent where required, or legitimate interests (such as system security).",
      ],
    },
    {
      title: "5. Third-party processors",
      paragraphs: [
        "We use (or may use) services that may process data outside Hong Kong, including Stripe (payments), Supabase (database, auth, file storage), a transactional email provider (e.g. Resend), Vercel (hosting), and others. Each has its own privacy policy.",
      ],
    },
    {
      title: "6. Retention (including after trial)",
      paragraphs: [
        "After trial ends (T+30): we send an email reminder.",
        "After trial ends (T+60): if still unsubscribed, we may delete the account and related business data.",
        "After trial ends (T+90): we fully purge remaining backups or receipt image files (Supabase Storage).",
        "Manual deletion: via the Account page; once triggered, the system starts the purge process immediately.",
      ],
    },
    {
      title: "7. Security",
      paragraphs: [
        "We use reasonable technical and organisational measures (e.g. HTTPS, access controls, vendor security features). Transmission over the internet is not 100% secure.",
      ],
    },
    {
      title: "8. Your rights",
      paragraphs: [
        "You may contact bookkeep@harbix.app to request access, correction, or (where law allows) deletion.",
        "After sign-in, open the Account page to delete your account: we remove your login, business data (ledgers, transactions, categories), and uploaded receipts, and we cancel Stripe subscriptions and delete the Stripe customer record linked to this app where possible; Stripe may retain some billing records under its own policies.",
      ],
    },
    {
      title: "9. Cookies",
      paragraphs: [
        "We use necessary cookies for sign-in and security; if we add analytics/marketing cookies later, we will update this policy and obtain consent where required.",
      ],
    },
    {
      title: "10. Children",
      paragraphs: [
        "The service is not intended for people under 18; if we learn we collected data by mistake, contact us to delete it.",
      ],
    },
    {
      title: "11. Policy changes",
      paragraphs: [
        "We may update this policy; material changes will be notified on the site or by email.",
      ],
    },
  ],
};

export function getTerms(locale: Locale): LegalDocument {
  return locale === "en" ? termsEn : termsZh;
}

export function getPrivacy(locale: Locale): LegalDocument {
  return locale === "en" ? privacyEn : privacyZh;
}
